# Generated by Django 5.1.1 on 2025-05-29 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacionPerfil', models.DateTimeField(auto_now_add=True)),
                ('fechaNacimiento', models.DateField()),
                ('bio', models.CharField(max_length=500)),
                ('imgPerfil', models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, null=True, upload_to='images_perfiles/'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
