# Generated by Django 5.1.1 on 2025-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='creacionPerfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='enlaces',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
