# Generated by Django 5.1.1 on 2025-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_perfil_creacionperfil_perfil_enlaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('imgPost', models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, null=True, upload_to='images_post/'))),
                ('likes', models.IntegerField(max_length=11)),
                ('comments', models.IntegerField(max_length=11)),
            ],
        ),
    ]
