# Generated by Django 5.1.1 on 2025-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
