# Generated by Django 5.1.1 on 2025-05-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_post_iduser_alter_post_comments_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idUser',
            field=models.IntegerField(null=True),
        ),
    ]
