# Generated by Django 5.1.6 on 2025-05-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_post_comments_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
