# Generated by Django 5.1.1 on 2025-06-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
