# Generated by Django 5.1.1 on 2025-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0009_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('publicado', models.BooleanField()),
                ('idUser', models.IntegerField()),
                ('username', models.CharField(max_length=500)),
            ],
        ),
    ]
