# Generated by Django 5.1.1 on 2025-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='image_field',
            field=models.ImageField(default='null', upload_to='images', verbose_name='image'),
        ),
    ]
