# Generated by Django 5.1.1 on 2025-06-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_posteos_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteos',
            name='username',
        ),
        migrations.AlterField(
            model_name='posteos',
            name='idUser',
            field=models.CharField(max_length=200),
        ),
    ]
