# Generated by Django 5.1.1 on 2025-06-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_remove_posteos_username_alter_posteos_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('foto_perfil', models.ImageField(default='null', upload_to='images', verbose_name='image')),
                ('biografia', models.CharField(max_length=400)),
                ('enlaces', models.CharField(max_length=500)),
                ('preferencias', models.CharField(max_length=500)),
            ],
        ),
    ]
