# Generated by Django 5.1.6 on 2025-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='null', upload_to='profile', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idUser',
            field=models.CharField(max_length=400),
        ),
    ]
