# Generated by Django 5.1.1 on 2025-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_remove_posteos_iduser_posteos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='null', upload_to='images', verbose_name='image'),
        ),
    ]
