# Generated by Django 5.1.1 on 2025-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_friendship_requestfriend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
