# Generated by Django 5.1.1 on 2025-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_comentario_compartir_reaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaccion',
            name='contenido',
        ),
    ]
