# Generated by Django 5.1.1 on 2025-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_remove_reaccion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='nom_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
