# Generated by Django 5.1.1 on 2025-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_posteos_nom_of_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('username', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='posteo',
            new_name='posteo_original',
        ),
        migrations.DeleteModel(
            name='Reaccion',
        ),
    ]
