# Generated by Django 5.1.1 on 2025-07-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_like_rename_posteo_comentario_posteo_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartir',
            name='user',
        ),
        migrations.AddField(
            model_name='compartir',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.perfil'),
        ),
    ]
