# Generated by Django 5.1.1 on 2025-07-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_remove_compartir_user_compartir_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.perfil'),
        ),
    ]
